CRUDS/CrudMvcSebasCastanoEF/CrudMvcSebasCastanoEF/Models/Editoriale.cs
using System;
using System.Collections.Generic;

namespace CrudMvcSebasCastanoEF.Models;

public partial class Editoriale
{
    public int Nit { get; set; }

    public string? Nombres { get; set; }

    public string? Telefono { get; set; }

    public string? Direccion { get; set; }

    public string? Email { get; set; }

    public string? Sitioweb { get; set; }

    public virtual ICollection<Libro> Libros { get; } = new List<Libro>();
}

CRUDS/CrudMvcSebasCastanoEF/CrudMvcSebasCastanoEF/Controllers/EditorialesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrudMvcSebasCastanoEF.Models;

namespace CrudMvcSebasCastanoEF.Controllers
{
    public class EditorialesController : Controller
    {
        private readonly BibliotecaContext _context;

        public EditorialesController(BibliotecaContext context)
        {
            _context = context;
        }

        // GET: Editoriales
        public async Task<IActionResult> Index(string buscar, string filtro)
        {
            var editoriales = from Editoriale in _context.Editoriales select Editoriale;

            if (!String.IsNullOrEmpty(buscar))
            {
                editoriales = editoriales.Where(s => s.Nombres!.Contains(buscar));
            }
            ViewData["FiltroNombre"] = String.IsNullOrEmpty(filtro) ?    "NombreDescendente" : "";
            ViewData["FiltroTelefono"] = filtro == "TelefonoAscendente" ? "TelefonoDescendente" : "TelefonoAscendente";


            switch (filtro)
            {
                case "NombreDescendente":
                    editoriales = editoriales.OrderByDescending(editoriales => editoriales.Nombres);
                    break;
                case "TelefonoDescendente":
                    editoriales = editoriales.OrderByDescending(editoriales => editoriales.Telefono);
                    break;
                case "TelefonoAscendente":
                    editoriales = editoriales.OrderBy(editoriales => editoriales.Telefono);
                    break;
                default:
                    editoriales = editoriales.OrderBy(editoriales => editoriales.Nombres);
                   // editoriales = editoriales.OrderBy(editoriales => editoriales.Telefono);
                    break;

            }

            return View(await editoriales.ToListAsync());
        }

        // GET: Editoriales/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Editoriales == null)
            {
                return NotFound();
            }

            var editoriale = await _context.Editoriales
                .FirstOrDefaultAsync(m => m.Nit == id);
            if (editoriale == null)
            {
                return NotFound();
            }

            return View(editoriale);
        }

        // GET: Editoriales/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Editoriales/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nit,Nombres,Telefono,Direccion,Email,Sitioweb")] Editoriale editoriale)
        {
            if (ModelState.IsValid)
            {
                _context.Add(editoriale);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(editoriale);
        }

        // GET: Editoriales/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Editoriales == null)
            {
                return NotFound();
            }

            var editoriale = await _context.Editoriales.FindAsync(id);
            if (editoriale == null)
            {
                return NotFound();
            }
            return View(editoriale);
        }

        // POST: Editoriales/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Nit,Nombres,Telefono,Direccion,Email,Sitioweb")] Editoriale editoriale)
        {
            if (id != editoriale.Nit)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(editoriale);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EditorialeExists(editoriale.Nit))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(editoriale);
        }

        // GET: Editoriales/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Editoriales == null)
            {
                return NotFound();
            }

            var editoriale = await _context.Editoriales
                .FirstOrDefaultAsync(m => m.Nit == id);
            if (editoriale == null)
            {
                return NotFound();
            }

            return View(editoriale);
        }

        // POST: Editoriales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Editoriales == null)
            {
                return Problem("Entity set 'BibliotecaContext.Editoriales'  is null.");
            }
            var editoriale = await _context.Editoriales.FindAsync(id);
            if (editoriale != null)
            {
                _context.Editoriales.Remove(editoriale);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EditorialeExists(int id)
        {
          return (_context.Editoriales?.Any(e => e.Nit == id)).GetValueOrDefault();
        }
    }
}

CRUDS/CrudMvcSebasCastanoEF/CrudMvcSebasCastanoEF/Views/Editoriales/Create.cshtml
@model CrudMvcSebasCastanoEF.Models.Editoriale

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Editoriale</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nit" class="control-label"></label>
                <input asp-for="Nit" class="form-control" />
                <span asp-validation-for="Nit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sitioweb" class="control-label"></label>
                <input asp-for="Sitioweb" class="form-control" />
                <span asp-validation-for="Sitioweb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUDS/CrudMvcSebasCastanoEF/CrudMvcSebasCastanoEF/Views/Editoriales/Delete.cshtml
@model CrudMvcSebasCastanoEF.Models.Editoriale

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Editoriale</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sitioweb)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sitioweb)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Nit" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CRUDS/CrudMvcSebasCastanoEF/CrudMvcSebasCastanoEF/Views/Editoriales/Details.cshtml
@model CrudMvcSebasCastanoEF.Models.Editoriale

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Editoriale</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sitioweb)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sitioweb)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Nit">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CRUDS/CrudMvcSebasCastanoEF/CrudMvcSebasCastanoEF/Views/Editoriales/Edit.cshtml
@model CrudMvcSebasCastanoEF.Models.Editoriale

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Editoriale</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Nit" />
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sitioweb" class="control-label"></label>
                <input asp-for="Sitioweb" class="form-control" />
                <span asp-validation-for="Sitioweb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUDS/CrudMvcSebasCastanoEF/CrudMvcSebasCastanoEF/Views/Editoriales/Index.cshtml
@model IEnumerable<CrudMvcSebasCastanoEF.Models.Editoriale>

@{
    ViewData["Title"] = "Index";
}

<h1>Editoriales
</h1>
<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>
<form asp-controller="Editoriales" asp-action="Index">
    <p>
        Buscar: <input type="text" name="buscar" class="form-text" />
        <input type="submit" value="buscar" class="btn btn-sm btn-dark" />

    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nit)

            </th>
            <th>
                <a asp-action="Index" asp-route-filtro="@ViewData["FiltroNombre"]">

                    @Html.DisplayNameFor(model => model.Nombres)
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-filtro="@ViewData["FiltroTelefono"]">

                    @Html.DisplayNameFor(model => model.Telefono)
                </a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sitioweb)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nit)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombres)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sitioweb)
            </td>
           
            <td>
                <a asp-action="Edit" class="btn btn-warning" asp-route-id="@item.Nit">Edit</a> 
                <a asp-action="Details" class="btn btn-primary" asp-route-id="@item.Nit">Details</a> 
                <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Nit">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>