CRUDS/CrudMvcSebasCastanoEF/CrudMvcSebasCastanoEF/Controllers/LibroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrudMvcSebasCastanoEF.Models;

namespace CrudMvcSebasCastanoEF.Controllers
{
    public class LibroesController : Controller
    {
        private readonly BibliotecaContext _context;

        public LibroesController(BibliotecaContext context)
        {
            _context = context;
        }

        // GET: Libroes
        public async Task<IActionResult> Index(string buscar, string filtro)
        {
            var libros = from Libro in _context.Libros select Libro;

            if (!String.IsNullOrEmpty(buscar))
            {
                libros = libros.Where(s => s.Titulo!.Contains(buscar));
            }
            ViewData["FiltroTitulo"] = String.IsNullOrEmpty(filtro) ? "TituloDescendente" : "";
            ViewData["FiltroFechaRegistro"] = filtro == "FechaRegistroAscendente" ? "FechaRegistroDescendente" : "FechaRegistroAscendente";


            switch (filtro)
            {
                case "TituloDescendente":
                    libros = libros.OrderByDescending(editoriales => editoriales.Titulo);
                    break;
                case "FechaRegistroDescendente":
                    libros = libros.OrderByDescending(editoriales => editoriales.FechaRegistro);
                    break;
                case "FechaRegistroAscendente":
                    libros = libros.OrderBy(editoriales => editoriales.FechaRegistro);
                    break;
                default:
                    libros = libros.OrderBy(editoriales => editoriales.Titulo);
                    // editoriales = editoriales.OrderBy(editoriales => editoriales.Telefono);
                    break;

            }

            return View(await libros.ToListAsync());
        }

        // GET: Libroes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Libros == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.CodigoCategoriaNavigation)
                .Include(l => l.NitEditorialNavigation)
                .FirstOrDefaultAsync(m => m.Isbn == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // GET: Libroes/Create
        public IActionResult Create()
        {
            ViewData["CodigoCategoria"] = new SelectList(_context.Categorias, "CodigoCategoria", "CodigoCategoria");
            ViewData["NitEditorial"] = new SelectList(_context.Editoriales, "Nit", "Nit");
            return View();
        }

        // POST: Libroes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Isbn,Titulo,Descripcion,NombreAutor,Publicacion,FechaRegistro,CodigoCategoria,NitEditorial")] Libro libro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(libro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CodigoCategoria"] = new SelectList(_context.Categorias, "CodigoCategoria", "CodigoCategoria", libro.CodigoCategoria);
            ViewData["NitEditorial"] = new SelectList(_context.Editoriales, "Nit", "Nit", libro.NitEditorial);
            return View(libro);
        }

        // GET: Libroes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Libros == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros.FindAsync(id);
            if (libro == null)
            {
                return NotFound();
            }
            ViewData["CodigoCategoria"] = new SelectList(_context.Categorias, "CodigoCategoria", "CodigoCategoria", libro.CodigoCategoria);
            ViewData["NitEditorial"] = new SelectList(_context.Editoriales, "Nit", "Nit", libro.NitEditorial);
            return View(libro);
        }

        // POST: Libroes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Isbn,Titulo,Descripcion,NombreAutor,Publicacion,FechaRegistro,CodigoCategoria,NitEditorial")] Libro libro)
        {
            if (id != libro.Isbn)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(libro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LibroExists(libro.Isbn))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CodigoCategoria"] = new SelectList(_context.Categorias, "CodigoCategoria", "CodigoCategoria", libro.CodigoCategoria);
            ViewData["NitEditorial"] = new SelectList(_context.Editoriales, "Nit", "Nit", libro.NitEditorial);
            return View(libro);
        }

        // GET: Libroes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Libros == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.CodigoCategoriaNavigation)
                .Include(l => l.NitEditorialNavigation)
                .FirstOrDefaultAsync(m => m.Isbn == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // POST: Libroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Libros == null)
            {
                return Problem("Entity set 'BibliotecaContext.Libros'  is null.");
            }
            var libro = await _context.Libros.FindAsync(id);
            if (libro != null)
            {
                _context.Libros.Remove(libro);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LibroExists(string id)
        {
          return (_context.Libros?.Any(e => e.Isbn == id)).GetValueOrDefault();
        }
    }
}

CRUDS/CrudMvcSebasCastanoEF/CrudMvcSebasCastanoEF/Views/Libroes/Create.cshtml
@model CrudMvcSebasCastanoEF.Models.Libro

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Isbn" class="control-label"></label>
                <input asp-for="Isbn" class="form-control" />
                <span asp-validation-for="Isbn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreAutor" class="control-label"></label>
                <input asp-for="NombreAutor" class="form-control" />
                <span asp-validation-for="NombreAutor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publicacion" class="control-label"></label>
                <input asp-for="Publicacion" class="form-control" />
                <span asp-validation-for="Publicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRegistro" class="control-label"></label>
                <input asp-for="FechaRegistro" class="form-control" />
                <span asp-validation-for="FechaRegistro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodigoCategoria" class="control-label"></label>
                <select asp-for="CodigoCategoria" class ="form-control" asp-items="ViewBag.CodigoCategoria"></select>
            </div>
            <div class="form-group">
                <label asp-for="NitEditorial" class="control-label"></label>
                <select asp-for="NitEditorial" class ="form-control" asp-items="ViewBag.NitEditorial"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUDS/CrudMvcSebasCastanoEF/CrudMvcSebasCastanoEF/Views/Libroes/Delete.cshtml
@model CrudMvcSebasCastanoEF.Models.Libro

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreAutor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreAutor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publicacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publicacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodigoCategoriaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodigoCategoriaNavigation.CodigoCategoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NitEditorialNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NitEditorialNavigation.Nit)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Isbn" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CRUDS/CrudMvcSebasCastanoEF/CrudMvcSebasCastanoEF/Views/Libroes/Details.cshtml
@model CrudMvcSebasCastanoEF.Models.Libro

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreAutor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreAutor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publicacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publicacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodigoCategoriaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodigoCategoriaNavigation.CodigoCategoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NitEditorialNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NitEditorialNavigation.Nit)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Isbn">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CRUDS/CrudMvcSebasCastanoEF/CrudMvcSebasCastanoEF/Views/Libroes/Edit.cshtml
@model CrudMvcSebasCastanoEF.Models.Libro

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Isbn" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreAutor" class="control-label"></label>
                <input asp-for="NombreAutor" class="form-control" />
                <span asp-validation-for="NombreAutor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publicacion" class="control-label"></label>
                <input asp-for="Publicacion" class="form-control" />
                <span asp-validation-for="Publicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRegistro" class="control-label"></label>
                <input asp-for="FechaRegistro" class="form-control" />
                <span asp-validation-for="FechaRegistro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodigoCategoria" class="control-label"></label>
                <select asp-for="CodigoCategoria" class="form-control" asp-items="ViewBag.CodigoCategoria"></select>
                <span asp-validation-for="CodigoCategoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NitEditorial" class="control-label"></label>
                <select asp-for="NitEditorial" class="form-control" asp-items="ViewBag.NitEditorial"></select>
                <span asp-validation-for="NitEditorial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUDS/CrudMvcSebasCastanoEF/CrudMvcSebasCastanoEF/Views/Libroes/Index.cshtml
@model IEnumerable<CrudMvcSebasCastanoEF.Models.Libro>

@{
    ViewData["Title"] = "Index";
}

<h1>Libros</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>

<form asp-controller="Libroes" asp-action="Index">
    <p>
        Buscar: <input type="text" name="buscar" class="form-text" />
        <input type="submit" value="buscar" class="btn btn-sm btn-dark" />

    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Isbn)

            </th>
            <th>
                <a asp-action="Index" asp-route-filtro="@ViewData["FiltroTitulo"]">

                    @Html.DisplayNameFor(model => model.Titulo)
                </a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreAutor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Publicacion)
            </th>
            <th>
                <a asp-action="Index" asp-route-filtro="@ViewData["FiltroFechaRegistro"]">

                    @Html.DisplayNameFor(model => model.FechaRegistro)
                </a>
            </th>
          
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    @Html.DisplayFor(modelItem => item.Isbn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreAutor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Publicacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaRegistro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodigoCategoriaNavigation.CodigoCategoria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NitEditorialNavigation.Nit)
            </td>
            <td>
                <a asp-action="Edit" class="btn btn-warning" asp-route-id="@item.Isbn">Edit</a> 
                <a asp-action="Details" class="btn btn-primary" asp-route-id="@item.Isbn">Details</a> 
                <a asp-action="Delete"  class = "btn btn-danger" asp-route-id="@item.Isbn">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>